### ISSUE TITLE
What caused the error

### ISSUE THREAD

**Issue by Xiao8426** [Mark-Yousri/YOLOv8-Object-Detection-on-Fish-Dataset#2]
![QQ图片20240323150722](https://github.com/Mark-Yousri/YOLOv8-Object-Detection-on-Fish-Dataset/assets/82746830/99d05c67-43c0-4289-b400-01a7fdc9ed55)

**Comment by Mark-Yousri** [comment]
Previously, I did not experience this problem when using Kaggle to run my notebook. Nevertheless, you should examine the section of your code where you supply the filename for the ReadFile function. Verify that a string, not a floating-point number, is the filename. Make that the variable for the filename is appropriately assigned a string value if you're using one.

**Comment by Xiao8426** [comment]
I just changed the DATA_PATH

**Comment by Mark-Yousri** [comment]
Try the data path link in the README file. and run it on Kaggle instead of running it locally, hope this helps.

**Comment by Xiao8426** [comment]
I am new to this and I want to know how to store this subfolder in the data set.

**Comment by Mark-Yousri** [comment]
Just put the path of the subfolder in the DATA_PATH variable
